### ISSUE TITLE
BETA PROGRAM - Raise issues by adding comments to this issue

### ISSUE THREAD

**Issue by kevinmcaleer** [kevinmcaleer/kevsrobots.com#9]
## This is the Learning Platform Beta program issue tracker
Please raise issues by adding comments to this issue.

I'm interested in all feedback you have, particularly:
* Correctness of code
* Course content
* Course navigation
* Look and feel

**Comment by lenzjo** [comment]
Course is looking good so far. Found a spelling mistake  on https://beta.kevsrobots.com/learn/micropython/09_example02.html. In the numbers program on the line:
    print('hello', name, 'now does', age, 'feel?')

I think you meant:
   print('hello', name, 'how does', age, 'feel?')

Also an odd one I can't reproduce. The first time I went thru the "how to use" course" the progress went to 50% at the end of the course, so I went thru it again and it carried on from 50% upto 100%. Now on every attempt it starts the course at 0% and finishes at 100%. This did not happen with the micropython course.

**Comment by d-c-d** [comment]
sorry - didn't see this ( so much for reading all the directions )
I added two issues 
 * https://github.com/kevinmcaleer/kevsrobots.com/issues/10
 *  https://github.com/kevinmcaleer/kevsrobots.com/issues/11

**Comment by d-c-d** [comment]
> Course is looking good so far. Found a spelling mistake on https://beta.kevsrobots.com/learn/micropython/09_example02.html. In the numbers program on the line: print('hello', name, 'now does', age, 'feel?')
> 
> I think you meant: print('hello', name, 'how does', age, 'feel?')
> 
> Also an odd one I can't reproduce. The first time I went thru the "how to use" course" the progress went to 50% at the end of the course, so I went thru it again and it carried on from 50% upto 100%. Now on every attempt it starts the course at 0% and finishes at 100%. This did not happen with the micropython course.

when I went through the course I got to 92% and it didn't have a 'next' link - ( I assumed it was just incomplete? )

**Comment by kevinmcaleer** [comment]
I'll check out the percentage calculation - currently it's taking the number of lessons in the whole course and diving that by 100 to get the percentage. I'll try changing that to see if I can make the last lesson always result in 100. It might be rounding down to the nearest number which might result in the last lesson being less than 100%.

**Comment by kevinmcaleer** [comment]
I've fixed the 100 percent issue, the last lesson should always be 100% (even if it jumps slight more that the previous pages).

**Comment by d-c-d** [comment]
thanks I now see that on [Modules](https://beta.kevsrobots.com/learn/micropython/17_modules.html) the 100%
the page that only has "prev", but no "next" is the last, but I'm guessing that more pages are to come, right?

**Comment by mattytrentini** [comment]
The course is looking great @kevinmcaleer! Here is some picky feedback (only 80% of the way through...).

## Why use MicroPython

Comparing to C++ doesn't seem very apples-to-apples. Idiomatic C++ would look like this:

```c++
#include <iostream>
void main(){
    std::cout << "hello world";
}
```
Which is not _terribly_ different.
I am struggling to come up with an alternative that is small enough not to overwhelm! 

## Python Development Environments 

Atom: Should probably remove from the list since Github is [Sunsetting Atom](https://github.blog/2022-06-08-sunsetting-atom/)

## Our First Program

[Black insists on double-quotes](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings) so, while it's good to explain that both are allowed, perhaps it's a good idea to at least use double-quotes for examples? Just to nudge beginners to get used to it from the start.

## Example 01

Minor point, but you've used a comment before explaining what they are? I'm not sure a beginner will actually notice though...

(Shifting the Note from Example 02 here would solve that issue.)

## Variables and Constants

Do you want to call out that `const()` is a MicroPython-only feature? 

Similarly, the MicroPython fact is actually a Python fact. Maybe prefixing with "Like Python, ..."

## Example 02

Typo: Lets->Let's (particularly noticeable because it directly follows the same use but with different spelling!).

*Really* hard to see the hash symbol in the Note (I think it's red-on-orange?).

"We've introduced something new"...but you introduced that in Variables and Constants!

Maybe ask for a surname instead of their age? I can see confusion when they try to apply math to their (string) age!

"...can use a formula - " May want to replace that dash with a colon. Otherwise it's easy to mistake "180" for "-180".

## If, elif, else

Same red-on-orange issue in the "Colons" and "Assumed True" boxouts.

Do you want to mention that blocks are defined by whitespace?

"Elif, a shorting of..." -> "Elif, a *shortening* of...". Also suggest putting quotes around the following 'else if' and maybe italicise it to help readability?

## Loops

The loop will start at 0, not 1.

Parameters/Arguments boxout: "...there is a difference a argument..."->"...there is a difference *between an* argument...". Also, I think "an parameter" should be "a parameter".

## Operators

Did you intend to explain that `a=10`, `b=20`?

Arithmetic Operators: Division - Answer should be 2.0 (ie a float). Floor division: Is that a wayward '-'? Otherwise the first result should be -5.

Assignment operators: 'into' in the Equals example shouldn't be formatted as code (super picky, sorry!). 

Logical Operators: Table headings are incorrect. Not example should use a lowercase `not`.

Bitwise operators: Did you intend to explain that `a=60`, `b=13`? Also missing "= 12" in Binary AND example.

**Comment by romilly** [comment]
High-level questions:
Who is the intended audience?
What, if any, are the course prerequisites?
What will they know or be able to do when they have completed the course?

**Comment by kevinmcaleer** [comment]
Thanks @romilly these are great questions - I've updated the introduction page to hopefully answer these. If you can take a look and give me your honest feedback I'd really appreciate it.

**Comment by romilly** [comment]
@kevinmcaleer That's really good! Simple, clear and specific.
